In [1]:
import pandas as pd
import time
start_time = time.time()

In [2]:
df = pd.read_csv("/Users/kashish/Downloads/dataset5.csv", header=None, delimiter=',', engine='python', names=range(100))
df = df.where((pd.notnull(df)), None)

In [3]:
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,magzines,papertowels,heavy cream,Mop,lotion,Soap,tea,deodrant,Oxiclean,oreos,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,t,t,t,None,t,None,t,t,t,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,t,None,t,t,None,None,None,None,None,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,None,t,None,t,None,t,t,None,t,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,t,t,None,None,t,None,t,None,None,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,t,None,t,None,t,None,t,t,t,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,None,None,None,t,t,None,t,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,t,t,t,None,t,t,None,t,t,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,None,None,t,None,None,None,t,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,t,None,None,None,None,t,None,t,None,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,None,None,t,None,t,None,t,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,t,None,None,None,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,None,None,None,t,None,t,t,None,None,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,t,t,None,None,t,None,None,None,t,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,None,None,t,None,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,t,None,None,None,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,None,None,None,t,None,None,t,t,None,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,t,t,None,None,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,None,None,None,None,None,None,None,None,t,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,t,None,None,t,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,None,t,None,None,None,None,t,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,None,None,None,None,t,None,t,t,None,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,t,None,None,None,None,None,None,None,t,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,None,t,None,None,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,t,None,t,None,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,None,None,None,None,None,None,None,t,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,None,None,None,None,None,None,t,None,t,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,t,None,t,None,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,None,None,None,None,t,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
ItemMatrix = \
    pd.get_dummies(df.unstack().dropna()).groupby(level=1).sum()
transactionCnt, itemCnt = ItemMatrix.shape
print('The number of transactions: ',transactionCnt)
print('The number of different items: ',itemCnt,'\n')
largeItemsets = []
for items in range(1, itemCnt+1):
    from itertools import combinations
    for itemset in combinations(ItemMatrix, items):
        itemset_Support = ItemMatrix[list(itemset)].all(axis=1).sum()
        s = [str(x) for x in itemset]
        if (len(s) >= 1):
            largeItemsets.append([",".join(s), itemset_Support])
freqItemset = pd.DataFrame(largeItemsets, columns=["Itemset", "Support"])
results = freqItemset[freqItemset.Support >= 2]
print(results)


dataFile = open('output.txt', 'w')

for eachitem in largeItemsets:
    dataFile.write(str(eachitem)+'\n')
dataFile.close()

print("--- %s seconds ---" % (time.time() - start_time))

The number of transactions:  29
The number of different items:  21